apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local:9090
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-config
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-files
data:
  kafka.json: |
    {
      "title": "Producer Event Metrics",
      "refresh": "5s",
      "timezone": "",
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "panels": [
        {
          "type": "stat",
          "title": "Total Events Sent",
          "gridPos": { "x": 0, "y": 0, "w": 12, "h": 7 },
          "targets": [
            {
              "expr": "producer_events_total",
              "legendFormat": "producer"
            }
          ],
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "auto"
          }
        },
        {
          "type": "timeseries",
          "title": "Events per Minute",
          "gridPos": { "x": 0, "y": 7, "w": 24, "h": 12 },
          "targets": [
            {
              "expr": "rate(producer_events_total[1m])",
              "legendFormat": "events/min"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "events/min"
            },
            "overrides": []
          },
          "options": {
            "legend": {
              "displayMode": "list",
              "placement": "bottom"
            }
          }
        }
      ],
      "schemaVersion": 39,
      "version": 1
    }

